name: CI/CD Pipeline Brenda

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Verifica si tu lab usa us-east-1 o us-west-2

      - name: Instalar dependencias
        run: |
          pip install flask boto3

      - name: Construir imagen de Docker
        run: |
          cd docker
          docker build -t mi-app-devops-test .